source 'https://rubygems.org'

ruby '3.0.0'

gem 'actionpack'
gem 'actionview'
gem 'activesupport', require: 'active_support/all'
gem 'ffi'
gem 'guard'
gem 'guard-rake'
gem 'loofah'
gem 'nokogiri'
gem 'rails-html-sanitizer'
gem 'rake'
gem 'rouge'