name: Build Static Site with Ruby Guides build system
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: compile
        run: rake guides:generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: backend-development/backend-development.github.io
          publish_branch: master
          publish_dir: ./output
